services:
  - type: web
    name: aesthetic-art-club-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      # Add your environment variables in Render dashboard instead
      # This is just a template

